### ISSUE TITLE
vkx parsing does not make sense...

### ISSUE THREAD

**Issue by jobarne** [vakaros/vkx#2]
I am trying to parse a vkx file. Following the specification, I analyze a vkx log file and view it in a HEX editor. When doing so, the output does not give reasonable data so obviously I have got the concept wrong. Can anyone give me a pointer in the right direction?

Here is an example of it not making sense:

ff (Page Header)
05 (VKX format 1.4 which makes sense)
20 20 9b 1c 20 20 (Internal log state)

0e (next "row" key is a Vakaros Internal Message)
b7 81 30 a2 91 01 20 20 ff ff ff ff ff ff ff ff (the 16 byte payload)

08 (next "row" key is Device Configuration)
b7 81 30 a2 91 01 20 20 (these 8 bytes should be unused so it having actual values makes me suspicisious...)
01 20 20 20 (4 bytes of Configuration Bitfield)
01 (logging rate of 1Hz which makes sense)

02 (next "row" is Position, Velocity, and Orientation and here is where the wheels really falls off)
b7 81 30 a2 91 01 20 20 (This should be Unix timestamp (ms UTC) but the value 13222903455712092192 is obviously not correct)
64 dc 89 1c (neither is 169.2174620 a correct Latitude)
d4 de 8b fd (same thing here)
20 20 20 20 
20 20 20 00 ...

What I am doing wrong?

**Comment by TNorbury** [comment]
Would you be able to share the .vkx file you're using so that I can take a look at it?

**Comment by jobarne** [comment]
Absolutely! Here it is:
[Benodet 30.8.2024.vkx.zip](https://github.com/user-attachments/files/16820870/Benodet.30.8.2024.vkx.zip)

**Comment by jonaswitt** [comment]
For what it's worth, that file loads fine in our implementation of the VKX format, so no issues with the file itself, I'd say.

**Comment by TNorbury** [comment]
@jobarne what is the hex viewer that you're using? I'm using https://hexed.it/, and also reading the file with the parser that we use in Connect, the timestamp values that I'm getting are B7 81 30 A2 91 01 00 00. It looks like the last two bytes for you got changed from `00` to `20`, converting those 8 bytes to a timestamp I get a time of 2024-08-30 07:29:33.623Z, UTC.

For the latitude: 64 DC 89 1C, I get a value of 47.879684999999995.

Our data is in little endian, which is why I think you're getting some weird values for lat/lng. If you're using a desktop calculator (I know this is true for MacOs, it's been a minute since I've used the one on Windows), they're in big endian, so you'll need to put the bytes in from right to left:
![image](https://github.com/user-attachments/assets/5f8f8775-28e9-4991-8778-a6b66a21f1cd)

As for the 00 bytes becoming 20, that's a mystery to me...

**Comment by jobarne** [comment]
Dear TNorbury!

Thanks a lot for these prompt and informative answers. I am afraid that in my ignorance I were not aware of this reverse order of the bytes in little endean. Once applying that logic, it all look good to me! Now I will be able to write a parser. Great!
